name: init-nodejs

inputs:
  nodejs-version:
    default: "14"
    required: false
    description: "version of nodejs"

runs:
  using: composite
  steps:
    - name: setup node ${{ inputs.nodejs-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.nodejs-version }}
        registry-url: https://npm.pkg.github.com/
        cache: "npm"
    - name: install
      if: steps.node_cache_id.outputs.cache-hit != 'true'
      shell: bash
      run: npm ci
