name: nodejs cron

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  npm-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: init nodejs
        uses: ./.github/actions/init
        with:
          nodejs-version: 16.x
      - uses: oke-py/npm-audit-action@v2.4.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dedupe_issues: true
